services:
  - type: web
    name: devdatasorter-bot
    env: python
    buildCommand: pip install -r requirements-render.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-70b-versatile
    scaling:
      minInstances: 1
      maxInstances: 1